language: ruby
dist: xenial
cache: bundler

addons:
  apt:
    packages:
      - libexpat1-dev
      - gettext
      - libglib2.0-dev
      - liborc-0.4-dev
      - libfftw3-dev
      - liblcms2-dev
      - libmagickwand-dev
      - libopenexr-dev
      - libcfitsio3-dev
      - libgif-dev
      - libgsf-1-dev
      - libmatio-dev
      - libopenslide-dev
      - libpango1.0-dev
      - libpoppler-glib-dev
      - librsvg2-dev
      - libwebp-dev
  homebrew:
    packages:
      # A simple way to install all dependencies.
      - vips
      - glib

cache:
  bundler: true
  directories: $HOME/vips/ext

matrix:
  include:
    - rvm: 2.4
    - rvm: 2.5
    - rvm: 2.6
    - rvm: 2.6
      os: osx
    - rvm: truffleruby
    - rvm: jruby-head
    - rvm: ruby-head
  allow_failures:
    - rvm: truffleruby
    - rvm: ruby-head
    - rvm: jruby-head

before_script:
  - bundle exec rake ext

script: 
  - bundle exec rake
